### ISSUE TITLE
The zcml directive interface registers the interfaces always in the global registry

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.component#10]
In https://bugs.launchpad.net/zope.component/+bug/1089340, @agroszer reported:

> Whereas the other registrations use

``` python
sm = zope.component.getSiteManager()
sm.register...
```

`zope.component.interface.provideInterface` does:

``` python
gsm = zope.component.getGlobalSiteManager()
gsm.registerUtility...
```

what does not fit with `z3c.baseregistry` well.

**Comment by jamadden** [comment]
No tests in zope.component break if `zope.component.interface` is changed to use `getSiteManager()` instead of `getGlobalSiteManager()`.

However, I'm not sure what the purpose of those functions (registering every interface ever provided as a utility) is, so I'm not sure what impact changing that would make. 

I use `z3c.baseregistry`, but I don't (to my knowledge) use those interface functions. 

For those that don't use `z3c.baseregistry`, there shouldn't be any impact at all.
