### ISSUE TITLE
Could not adapt error silently swallows exceptions in adaption

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.component#11]
In https://bugs.launchpad.net/zope.component/+bug/1181749, @djay reported:

> If there is an exception in the factory when creating the adapter, `zope.component` will silently move on to the next adapter and eventually give a "could not adapt" error. This makes it very hard to debug such an error since you first have to guess what factories might be being called and then guess where the exception could be coming from. Is there a way we could have more meaningful stacktrace or logs which give clues to the swallowed exception?

**Comment by jamadden** [comment]
Even in the versions of zope.interface and zope.component published at the time of the original bug report (2013), I'm not finding a place during adaptation where we call a factory and ignore any exceptions it throws. This includes using a chained factory registered from ZCML.

There were a number of bare `except:` statements (and the moral equivalent in the C code) in zope.interface, and that could hide errors in `implementedBy`, `providedBy`, `obj.__conform__` and so on, many of which are used during the adaptation process. 

Those were all removed in zope.interface 5.1 in favor of `except AttributeError:`, so many errors no longer pass silently.

Because of that, I think this can be closed. If it's still a problem, please feel free to re-open with some additional details.
